management:
  endpoints:
    web:
      exposure:
        include: env

security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10

spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud
  rabbitmq:
    host: localhost
    port: 5672
    username: tacoweb
    password: letm31n

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
